apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  labels:
    app: demo-app
data:
  # Application settings
  APP_COLOR: "#e6f7ff"  # Light blue color
  ENV: "production"
  # Other configuration parameters can be added here
