apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  labels:
    app: demo-app
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'demo-api-key-12345' | base64
  API_KEY: ZGVtby1hcGkta2V5LTEyMzQ1
